---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: documents
- type: document
  path: _config.yml
  label: Configuration
- type: directory
  path: _authors
  label: Authors
  create: documents
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/nadliw45/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: jekyll serve --drafts --unpublished --future -d _site
