name: My workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to aidanblog.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'aidanblog.surge.sh'
          project: './special-octo-meme'
          login: 'me@wildanfauzy.com'
          token: '4a7a2ac211b6ce4ee840867e51d00e2d'
